apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
    app.kubernetes.io/instance: adminweb
  name: adminweb-redirect-https
spec:
  redirectScheme:
    permanent: true
    scheme: https