apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
    app.kubernetes.io/instance: adminweb
  name: adminweb-redirect-https
spec:
  redirectScheme:
    permanent: true
    scheme: https
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: adminweb-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /admin-web